name: "My Github Action Test"
description: "Test"

inputs:
  GITHUB_TOKEN:
    description: "Github token"
    default: ${{ github.token }}
    required: false
  COMMITTER_USERNAME:
    description: "Commit username"
    default: "blog-outline-bot"
    required: false
  COMMITTER_EMAIL:
    description: :"Commit email"
    default: "blog-outline-bot@exapmle.com"
    required: false
  MAX_LINES:
    description: "Maxium number of lines"
    default: "5"
    required: false
  COMMIT_MSG:
    description: "Commit message"
    default: "Update blog outline"
    required: false
  COMMIT_OWNER:
    description: "Commit owner"
    default: "Update owner"
    required: false
  COMMIT_REPO:
    description: "Commit repo"
    default: "Update repo"
    required: false
  COMMIT_PATH:
    description: "Path to directory in the repo"
    default: ""
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'