on: [push]

jobs:
  update_readme_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates_README
    steps:
      - uses: actions/checkout@v3
      - name: Updates_README
        uses: kerong2002/github_action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTER_EMAIL: ${{ secrets.EMAIL_SECRET }}
          COMMITTER_USERNAME: "kerong2002"
          COMMIT_REPO: "github_action"
          COMMIT_OWNER: "kerong2002"
