on: [push]

jobs:
  update_readme_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates_README
    steps:
      - uses: actions/checkout@3
      - name: Updates_README
        uses: kerong2002/github_action@main
