on: [push]

jobs:
  update_readme_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    - name: Count .cpp files
      run: |
        count=$(find . -name "*.cpp" | wc -l)
        echo "::set-output name=cpp_count::$count"
      id: count_cpp

    - name: Do something with the count
      run: |
        echo "There are ${{ steps.count_cpp.outputs.cpp_count }} .cpp files in the repository"

    name: Updates_README
    steps:
      - uses: actions/checkout@v3
      - name: Updates_README
        uses: kerong2002/github_action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTER_USERNAME: "kerong2002"
          COMMITTER_EMAIL: "krameri120@gmail.com"
          COMMIT_REPO: "github_action"
          COMMIT_OWNER: "kerong2002"